### ISSUE TITLE
Integrate Chain of Custody

### ISSUE THREAD

**Issue by y0sh1** [l0ngestever/logboek#1]
## Chain of Custody

The Chain of Custody is an fundamental paper trail within a (digital) forensic investigation. This paper trail contains everything from obtaining, handling, maintaining, controlling, transferring, analyzing of and the disposition of evidence materials.

## Goal

The goal of having this chain of custody paper trail is to maintain and provide documents which show every step taken with the evidence material, within the investigation. This is to show the material is properly handled, maintained and managed throughout the course of the investigation. A part of this maintenance is the transfer of material to and from people and storage, integrity checking (and integrity properties of) the evidence material.

## Content

I think the initial version of this chain of custody form should have the following fields/parameters

- Company (usually needed in projects)
- Transferred material
- Integrity check possibilities of the material
- Integrity check value of the material
- From details
- To details
- Signature of both parties.

**Comment by l0ngestever** [comment]
Function added. Issue closed.
